holoocean:
  holoocean_node:
    ros__parameters:
      draw_arrow: false
      show_viewport: true
      relative_path: true
      scenario_path: 'config/usv_auv.json'
      publish_commands: true
      # render_quality: 0
      
